# Query 10: Get offers for a given product which fulfill specific requirements

PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX bsbm-inst-data: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT DISTINCT ?offer ?price
WHERE {
	?offer bsbm:product bsbm-inst-data:Product15 .
	?offer bsbm:vendor ?vendor .
	?offer dc:publisher ?vendor .
	?vendor bsbm:country <http://downlode.org/rdf/iso-3166/countries#GB> .
	?offer bsbm:deliveryDays ?deliveryDays .
	FILTER (?deliveryDays <= 3)
	?offer bsbm:price ?price .
	?offer bsbm:validTo ?date .
	FILTER (?date > "2000-01-01T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime>)
}
LIMIT 10
